BreakOutBoxAuth/Controllers/GroepBeherenController.cs
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using BreakOutBoxAuth.hubs;
using BreakOutBoxAuth.Models;
using BreakOutBoxAuth.Models.Domain;
using BreakOutBoxAuth.Models.SessieViewModel;
using Microsoft.AspNet.SignalR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Differencing;

namespace BreakOutBoxAuth.Controllers
{
    public class GroepBeherenController : Controller
    {
        private readonly IGroepRepository _groepRepository;
        private readonly ISessieRepository _sessieRepository;
        private readonly IGroepstateRepository _groepstateRepository;
        private readonly AppHub _hub;
        
        public GroepBeherenController(IGroepRepository groepRepository, ISessieRepository sessieRepository,
            IGroepstateRepository groepstateRepository)
        {
            _groepRepository = groepRepository;
            _sessieRepository = sessieRepository;
            _groepstateRepository = groepstateRepository;
            
        }

        [Microsoft.AspNetCore.Authorization.Authorize(Policy = "Admin")]
        public IActionResult Index()
        {
            var sessies = _sessieRepository.GetAll();
            return View(sessies);
        }

        [Microsoft.AspNetCore.Authorization.Authorize(Policy = "Admin")]
        public IActionResult Groepen(string id)
        {
            Sessie sessie = _sessieRepository.GetByIdGroepenMetGroepstate(id);

            if (sessie == null)
            {
                return NotFound();
            }

            Groepstate state;

            foreach (var sessieGroep in sessie.SessieGroep)
            {
                if (sessieGroep.Groepen.Currentstate == null)
                {
                    sessieGroep.Groepen.InitializeState();
                }
            }

            _sessieRepository.SaveChanges();

            return View(sessie);
        }

        [Microsoft.AspNetCore.Authorization.Authorize(Policy = "Admin")]
        public IActionResult DeBlokkeer(decimal groepsId, string sessieId)
        {
            var groep = _groepRepository.GetById(groepsId);

            if (groep == null)
            {
                return NotFound();
            }

            if (groep.Currentstate.GetStateEnum() == State.BLOK)
            {
                groep.Spelen();
                groep.ResetFout();
                Groepstate state = groep.Currentstate;

                _groepRepository.SaveChanges();

                _groepstateRepository.Delete(state);
                _groepstateRepository.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Groepen), new {Id = sessieId});
        }

        [Microsoft.AspNetCore.Authorization.Authorize(Policy = "Admin")]
        public IActionResult GroepenActiveren(string sessieId)
        {
            var sessie = _sessieRepository.GetByIdGroepenMetGroepstate(sessieId);

            if (sessie == null)
            {
                return NotFound();
            }

            bool hasChanged = false;

            foreach (var sessieGroep in sessie.SessieGroep)
            {
                var state = sessieGroep.Groepen.Currentstate;
                if (sessieGroep.Groepen.Currentstate.GetStateEnum() == State.START ||
                    sessieGroep.Groepen.Currentstate.GetStateEnum() == State.GEKOZENVERGRENDELD)
                {
                    sessieGroep.Groepen.GekozenEnVergrendeld();

                    sessieGroep.Groepen.KanSpelen();
                    hasChanged = true;

                    _groepstateRepository.Delete(state);
                }
            }
 
            if (hasChanged)
            {
                _sessieRepository.SaveChanges();
                _groepstateRepository.SaveChangesAsync();

            }

            
            
            
            
            return RedirectToAction(nameof(Groepen), new {Id = sessieId});
        }
    }
}

BreakOutBoxAuth/Views/GroepBeheren/Groepen.cshtml
@using BreakOutBoxAuth.Models.Domain
@model BreakOutBoxAuth.Models.Sessie
<meta http-equiv="refresh" content="5" />


<div class="sessiebar">
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <input class="mdl-textfield__input" type="number" id="sample" value="@Model.Code" disabled>
        <label class="mdl-textfield__label" for="sample">@Model.Naam</label>
        <span class="mdl-textfield__error">Input is not a number!</span>
    </div>
</div>
<div class="secties">
    <div class="textback">
        <h2 class="container">Groepen Beheren</h2>
    </div>
    <div class="groepen container" id="sessies">
        <table class="table mdl-shadow--2dp">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Groep</th>
                    <th scope="col">Klas</th>
                    <th scope="col">Leerlingen</th>
                    <th scope="col">Vooruitgang</th>
                    <th scope="col">Status</th>
                    <th scope="col">DeBlokkeer</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var groep in Model.SessieGroep)
                {

                    <tr>
                        <td>
                            @groep.Groepen.Naam
                        </td>
                        <td>@groep.Groepen.Klas</td>
                        <td data-toggle="modal" data-target="#@groep.Groepen.Naam">Leerlingen</td>
                        <td>@(groep.Groepen.Progress -1) / @(groep.Groepen.GroepPad.Count)</td>
                        <td>@groep.Groepen.Currentstate.GetStatus()</td>
                        @if (groep.Groepen.Currentstate.GetStateEnum() == State.BLOK)
                        {
                            <td><a class="btn btn-primary" asp-controller="GroepBeheren" asp-action="DeBlokkeer" asp-route-groepsId="@groep.Groepen.Id" asp-route-sessieId="@Model.Naam" role="button">DeBlokkeer</a></td>
                        }
                        else
                        {
                            <td>Is niet geblokkeerd</td>
                        }

                    </tr>
                    <div class="modal fade" id="@groep.Groepen.Naam" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLongTitle">@groep.Groepen.Naam | @groep.Groepen.Klas</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" for="checkbox-2">
                                        <span class="mdl-checkbox__label">Contactleer:</span>
                                        <input type="checkbox" disabled id="checkbox-2" class="mdl-checkbox__input" @(groep.Groepen.Contactleer ? "checked" : "")>
                                    </label>
                                    <p>Leerlingen:</p>
                                    <ul class="demo-list-icon mdl-list">
                                        @foreach (var leerling in @groep.Groepen.LijstLeerlingen())
        {
                                <li class="mdl-list__item">
                                    <span class="mdl-list__item-primary-content">
                                        <i class="material-icons mdl-list__item-icon">person</i>
                                        @leerling
                                    </span>
                                </li>
}
                                    </ul>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="mdl-button mdl-js-button mdl-js-ripple-effect" data-dismiss="modal">Close</button>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </tbody>
        </table>
        <a class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" asp-controller="GroepBeheren" asp-action="GroepenActiveren" asp-route-sessieId="@Model.Naam" role="button">Activeer groepen</a>



    </div>
</div>

BreakOutBoxAuth/Views/GroepBeheren/index.cshtml
@model IEnumerable<BreakOutBoxAuth.Models.Sessie>
@{
    ViewData["Title"] = "Sessie selecteren";
    int counter = 1;
}
<div class="textback">
    <h2 class="container">@ViewData["Title"]</h2>
</div>
<div class="sessies container" id="sessies">
    <table class="table mdl-shadow--2dp">
        <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Sessienaam</th>
                <th scope="col">Startdatum</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var sessie in Model)
            {

                <tr onclick="location.href = '@(Url.Action("Groepen", "GroepBeheren", new {id = @sessie.Naam} ))'">
                    <th scope="row">@counter</th>
                    <td>
                        @sessie.Naam
                    </td>
                    <td>@sessie.Startdatum.ToString("dd/MM/yyyy")</td>

                </tr>
                counter++;
            }
        </tbody>
    </table>
</div>