BreakOutBoxAuth/Models/Domain/Groep.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using BreakOutBoxAuth.Models.Domain;
using Newtonsoft.Json;
using SQLitePCL;

namespace BreakOutBoxAuth.Models
{
    [JsonObject(MemberSerialization.OptIn)]
    public class Groep
    {
        public Groep()
        {
            GroepPad = new HashSet<GroepPad>();
            Groepstate = new HashSet<Groepstate>();
            SessieGroep = new HashSet<SessieGroep>();

//            ToState(new Groepgekozenstate(this));
        }

        [JsonProperty] public decimal Id { get; set; }
        public bool Contactleer { get; set; }
        public string Klas { get; set; }
        public string Naam { get; set; }
        public int Progress { get; set; }
        public Groepstate Currentstate { get; set; }
        public ICollection<GroepPad> GroepPad { get; set; }
        public ICollection<Groepstate> Groepstate { get; set; }
        public ICollection<SessieGroep> SessieGroep { get; set; }
        public string Leerlingen { get; set; }
        public int? CurrentstateId { get; set; }
        public int Fout { get; set; }


        public void Blok()
        {
            Currentstate.Blok();
        }

        public void Spelen()
        {
            Currentstate.Spelen();
        }

        public void Finish()
        {
            Currentstate.Finish();
        }

        public void KanSpelen()
        {
            Currentstate.KanSpelen();
        }

        public void GekozenEnVergrendeld()
        {
            Currentstate.GekozenEnVergrendeld();
        }

        public void ToState(Groepstate state)
        {
            Currentstate = state;
        }

        public ICollection<string> LijstLeerlingen()
        {
            ICollection<string> leerling = Leerlingen.Substring(0, Leerlingen.Length - 2).Split(",");
            return leerling;
        }

        private IDictionary<int, GroepPad> ConvertGroepPaden()
        {
            IDictionary<int, GroepPad> paden = new Dictionary<int, GroepPad>();
            foreach (var pad in GroepPad)
            {
                paden.Add(pad.PadenKey, pad);
            }

            return paden;
        }

        public GroepPad getCurrentGroepPad(int key)
        {
            return ConvertGroepPaden()[key];
        }

        public void InitializeState()
        {
            ToState(new GroepStartState(this));
        }

        public void VerhoogProgress()
        {
            Progress++;
        }

        public void VerhoogFout()
        {
            Fout++;
        }

        public void ResetFout()
        {
            Fout = 0;
        }

        public int GetProgress100()
        {
            Double progress = Convert.ToDouble(Progress);
            Double count = Convert.ToDouble(GroepPad.Count);

            return Convert.ToInt32(Math.Floor((progress / count) * 100));
        }
    }
}

BreakOutBoxAuth/Models/Domain/Oefening.cs
using System.Collections.Generic;
using Newtonsoft.Json;

namespace BreakOutBoxAuth.Models
{
    [JsonObject(MemberSerialization.OptIn)]
    public class Oefening
    {
        public Oefening()
        {
            BobOefening = new HashSet<BobOefening>();
            OefeningDoelstellingscode = new HashSet<OefeningDoelstellingscode>();
            OefeningGroepsbewerking = new HashSet<OefeningGroepsbewerking>();
            Pad = new HashSet<Pad>();
        }

        [JsonProperty] public string Naam { get; set; }
        [JsonProperty] public string Antwoord { get; set; }
        [JsonProperty] public string Feedback { get; set; }
        [JsonProperty] public string Opgave { get; set; }
        [JsonProperty] public int Tijdslimiet { get; set; }
        [JsonProperty] public string VakNaam { get; set; }
        [JsonProperty] public Vak VakNaamNavigation { get; set; }
        public ICollection<BobOefening> BobOefening { get; set; }
        public ICollection<OefeningDoelstellingscode> OefeningDoelstellingscode { get; set; }
        public ICollection<OefeningGroepsbewerking> OefeningGroepsbewerking { get; set; }
        public ICollection<Pad> Pad { get; set; }
    }
}

BreakOutBoxAuth/Models/LoungeViewModel/LoungeViewModel.cs
using System;

namespace BreakOutBoxAuth.Models.LoungeViewModel
{
    public class LoungeViewModel
    {
        public LoungeViewModel(Groep groep)
        {
            Groep = groep;
        }

        public LoungeViewModel()
        {
            
        }

       
        public Groep Groep { get; set; }
        
    }
}

BreakOutBoxAuth/Models/OefeningViewModel/FeedbackViewModel.cs
namespace BreakOutBoxAuth.Models.OefeningViewModel
{
    public class FeedbackViewModel
    {
        public FeedbackViewModel()
        {
            
        }

        public FeedbackViewModel(Groep groep, string feedback)
        {
            Groep = groep;
            Feedback = feedback;
        }
        
        public Groep Groep { get; set; }
        public string Feedback { get; set; }
        
    }
}

BreakOutBoxAuth/Controllers/GroepController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Data;
using System.IO;
using System.Linq;
using BreakOutBoxAuth.Models;
using BreakOutBoxAuth.Models.ActionViewModel;
using BreakOutBoxAuth.Models.Domain;
using BreakOutBoxAuth.Models.OefeningViewModel;
using Microsoft.AspNetCore.Mvc;
using Renci.SshNet;
using System.Linq;
using System.Timers;
using System.Web;
using BreakOutBoxAuth.Extensions;
using BreakOutBoxAuth.Models.LoungeViewModel;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Remotion.Linq.Clauses.ResultOperators;

namespace BreakOutBoxAuth.Controllers
{
    public class GroepController : Controller
    {
        private readonly IGroepRepository _groepRepository;
        private readonly SessionExtension _sessionExtension;
        private readonly ISessieRepository _sessieRepository;

        public GroepController(IGroepRepository groepRepository, ISessieRepository sessieRepository)
        {
            _groepRepository = groepRepository;
            _sessieRepository = sessieRepository;
            _sessionExtension = new SessionExtension();
        }

        public IActionResult Index(string id)
        {
            Sessie sessie = _sessieRepository.GetById(id);

            if (sessie == null)
            {
                return NotFound();
            }

            
            return View(sessie);
        }

        public IActionResult Lounge(decimal id)
        {
            Groep groep = _groepRepository.GetById(id);

            if (groep == null)
            {
                return NotFound();
            }


            if (groep.Currentstate == null)
            {
                groep.InitializeState();
                groep.GekozenEnVergrendeld();
                //groep.KanSpelen();
                //groep.Spelen();
                _groepRepository.SaveChanges();
            }
            else if (groep.Currentstate.GetStateEnum() == State.BLOK)
            {
                return RedirectToAction("Feedback", "Groep", new {Id = groep.Id});
            }else if (groep.Currentstate.GetStateEnum() == State.FINISH)
            {
                return RedirectToAction("Schatkist", "Groep");
            }
            
            


            return View(new LoungeViewModel(groep));
        }

        public IActionResult Start(decimal id)
        {
            Groep groep = _groepRepository.GetById(id);

            if (groep == null)
            {
                return NotFound();
            }

            switch (groep.Currentstate.GetStateEnum())
            {
                case State.KANSPELEN:
                    groep.Spelen();
                    _groepRepository.SaveChanges();
                    break;
                case State.FINISH:
                    return RedirectToAction("Schatkist", "Groep");
                    break;
                
                case State.BLOK:
                    return RedirectToAction("Feedback", "Groep", new {Id = groep.Id});
                    break;
                default:
                    
                    
                    return RedirectToAction("Index", "Groep", new {Id = groep.Id});
                    break;

            }
            /*//groep.InitializeState();
                //groep.KanSpelen();
                //groep.Spelen();
                //_groepRepository.SaveChanges();
                
                groep.Spelen();
                _groepRepository.SaveChanges();
            }else if (groep.Currentstate.GetStateEnum() == State.FINISH)
            {
                return RedirectToAction("Schatkist", "Groep");
            }else if (groep.Currentstate.GetStateEnum() == State.BLOK)
            {
                return RedirectToAction("Feedback", "Groep", new {Id = groep.Id});
            }
*/

            
            
            

            /*if (groep.Fout == 3)
            {
                if (groep.Contactleer)
                {
                    groep.Blok();
                    _groepRepository.SaveChanges();
                }

                return RedirectToAction("Feedback", "Groep", new {Id = groep.Id});
            }*/


            Pad pad = groep.getCurrentGroepPad(groep.Progress).Paden;
            ViewData["Oefening"] = pad.OefeningNaamNavigation;
            getFile(pad.OefeningNaamNavigation.Opgave);
            return View(new AntwoordViewModel(pad, groep));
        }

        public IActionResult StartDirect(decimal id)
        {
            Groep groep = _groepRepository.GetById(id);
            groep.VerhoogProgress();
            _groepRepository.SaveChanges();

            if (groep.Progress <= groep.GroepPad.Count)
            {
                return RedirectToAction("Start", "Groep", new {Id = groep.Id});
            }
            else
            {
                return View("Schatkist");
            }
        }


        [HttpPost]
        public IActionResult Start(decimal id, AntwoordViewModel antwoordViewModel)
        {
            var groep = _groepRepository.GetById(id);

            if (groep == null)
            {
                return NotFound();
            }


            if (groep.getCurrentGroepPad(groep.Progress).Paden.Antwoord.Equals(antwoordViewModel.Antwoord))
            {
                groep.ResetFout();
                
                _groepRepository.SaveChanges();
                if (groep.Contactleer)
                {
                    return RedirectToAction("Action", "Groep", new {Id = groep.Id});
                }
                else
                {
                    groep.VerhoogProgress();
                    _groepRepository.SaveChanges();
                    if (groep.Progress <= groep.GroepPad.Count)
                    {
                        return RedirectToAction("Start", "Groep", new {Id = groep.Id});
                    }
                    else
                    {
                        return View("Schatkist");
                    }
                }
            }
            else
            {
                TempData["error"] = "Oplossing fout!";
                if (groep.Fout == 3)
                {
                    groep.Blok();
                    _groepRepository.SaveChanges();

                    return RedirectToAction("Feedback", "Groep", new {Id = groep.Id});
                }
                else if (groep.Fout < 3)
                {
                    groep.VerhoogFout();
                    _groepRepository.SaveChanges();

                    if (groep.Fout == 3)
                    {
                        groep.Blok();
                        _groepRepository.SaveChanges();

                        return RedirectToAction("Feedback", "Groep", new {Id = groep.Id});
                    }
                }
            }


            return RedirectToAction("Start", "Groep", new {Id = groep.Id});
        }


        public IActionResult Feedback(decimal id)
        {
            Groep groep = _groepRepository.GetById(id);

            if (groep == null)
            {
                return NotFound();
            }


            string feedback = groep.getCurrentGroepPad(groep.Progress).Paden.OefeningNaamNavigation.Feedback;

            getFile(feedback);

            return View(new FeedbackViewModel(groep, feedback));
        }

        public IActionResult ExpiredTimer(decimal id)
        {
            Groep groep = _groepRepository.GetById(id);

            if (groep.Contactleer)
            {
                groep.Blok();
                _groepRepository.SaveChanges();
            }

            return RedirectToAction("Feedback", "Groep", new {Id = groep.Id});
        }

        public IActionResult Action(decimal id)
        {
            Groep groep = _groepRepository.GetById(id);

            if (groep == null)
            {
                return NotFound();
            }

            if (groep.getCurrentGroepPad(groep.Progress).Paden.ActieNaamNavigation == null)
            {
                return View(new ActionViewModel(groep.getCurrentGroepPad(groep.Progress).Paden, groep, true,
                    "Zoek de schatkist"));
            }

            return View(new ActionViewModel(groep.getCurrentGroepPad(groep.Progress).Paden, groep, false));
        }

        [HttpPost]
        public IActionResult Action(decimal id, ActionViewModel actionViewModel)
        {
            Groep groep = _groepRepository.GetById(id);

            if (groep == null)
            {
                return NotFound();
            }

            Pad pad = groep.getCurrentGroepPad(groep.Progress).Paden;

            if (pad.Toegangscode.Code == actionViewModel.Toegangscode)
            {
                if (groep.getCurrentGroepPad(groep.Progress).Paden.ActieNaamNavigation == null)
                {
                    groep.Finish();
                    _groepRepository.SaveChanges();
                    return View("Schatkist");
                }


                groep.VerhoogProgress();

                _groepRepository.SaveChanges();

                return RedirectToAction("Start", "Groep", new {Id = groep.Id});
            }
            else
            {
                if (groep.Fout == 3)
                {
                    groep.Blok();
                }
                else
                {
                    groep.VerhoogFout();
                }
            }

            return View(new ActionViewModel(pad, groep, false));
        }

        public IActionResult Schatkist()
        {
            return View();
        }

        private void getFile(string filename)
        {
            try
            {
                string host = "188.166.36.83";
                string username = "bob";
                string password = "Pazaak2.0";
                string remoteDirectory = "/uploads/"; // . always refers to the current directory.

BreakOutBoxAuth/Controllers/SessieController.cs
using BreakOutBoxAuth.Extensions;
using BreakOutBoxAuth.Models.Domain;
using BreakOutBoxAuth.Models.SessieViewModel;
using Microsoft.AspNetCore.Mvc;

namespace BreakOutBoxAuth.Controllers
{
    public class SessieController : Controller
    {
        private readonly ISessieRepository _sessieRepository;
        private readonly SessionExtension _sessionExtension;
        
        public SessieController(ISessieRepository sessieRepository)
        {
            _sessieRepository = sessieRepository;
            _sessionExtension = new SessionExtension();
        }

        // GET
        public IActionResult Index()
        {
            // Use this for development purpose
            //var sessies = _sessieRepository.GetAll();
            
            
            //var sessies = _sessieRepository.GetAllActive();
            var sessies = _sessieRepository.GetAllToday();
            return View(new SessieViewModel(sessies));
        }

        [HttpPost]
        public IActionResult Index(string id, SessieViewModel model
        )
        {
            var sessie = _sessieRepository.GetById(id);
            if (model.Code == sessie.Code)
            {

                
                return RedirectToAction("Index", "Groep", new { Id = sessie.Naam }); 
            }
            TempData["error"] = "Foute Sessiecode, probeer opnieuw";
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult Code(SessieViewModel model)
        {
            var sessie = _sessieRepository.GetByCode(model.Code);
            if (sessie != null)
            {
                return RedirectToAction("Index", "Groep", new {Id = sessie.Naam});
            }
            TempData["error"] = "Foute Sessiecode, probeer opnieuw";
            return RedirectToAction(nameof(Index));
        }
    }
}

BreakOutBoxAuth/Views/Groep/Action.cshtml
@using Microsoft.CodeAnalysis.CSharp.Syntax
@model BreakOutBoxAuth.Models.ActionViewModel.ActionViewModel

<div class="container">
    @if (Model.IsSchatkist)
    {
    <form method="post" >
        <div class="logcard mdl-card mdl-shadow--2dp">
            <div class="mdl-card__title">
                <h1 class="mdl-card__title-text">Actie</h1>
            </div>
            <div class="mdl-card__supporting-text">
                <h5>@Model.Opgave</h5>
            </div>
            <div class="mdl-card__actions mdl-card--border">
                <div>
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                        <input asp-for="Toegangscode" class="mdl-textfield__input" type="number" placeholder="Voeg het gevonden nummer in!" value="" id="actie">
                        <label class="mdl-textfield__label" for="actie">Antwoord</label>
                    </div>
                </div>
                <div>
                    <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" type="submit">Controlleer</button>
                </div>
            </div>
        </div>
    </form>
    }
    else
    {
        <form method="post" action="/Groep/Action/@Model.Groep.Id">
            <div class="logcard mdl-card mdl-shadow--2dp">
                <div class="mdl-card__title">
                    <h1 class="mdl-card__title-text">Actie</h1>
                </div>
                <div class="mdl-card__supporting-text">
                    <h5>@Model.Pad.ActieNaamNavigation.Opgave</h5>
                </div>
                <div class="mdl-card__actions mdl-card--border">
                    <div>
                        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                            <input asp-for="Toegangscode" class="mdl-textfield__input" type="number" placeholder="Voeg het gevonden nummer in!" value="" id="actie">
                            <label class="mdl-textfield__label" for="actie">Antwoord</label>
                        </div>
                    </div>
                    <div>
                        <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" type="submit">Controlleer</button>
                    </div>
                </div>
            </div>            
        </form>
    }
    
</div>

BreakOutBoxAuth/Views/Groep/Feedback.cshtml
@using BreakOutBoxAuth.Models.Domain
@model BreakOutBoxAuth.Models.OefeningViewModel.FeedbackViewModel
<meta http-equiv="refresh" content="10" />
<div class="gamescherm">
    <div class="container">
        <h1>Gamescherm</h1>
        <h2>@Model.Groep.Naam | Geblokkeerd</h2>
        <h3>Uw Feedback</h3>
        <a href="#oef" class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored">
            <i class="material-icons">keyboard_arrow_down</i>
        </a>
    </div>
</div>
<div class="textback"  id="oef">
    <h2 class="container">STATUS</h2>
</div>
<div class="container">
    <section class="feedback">
        @if (@Model.Groep.Currentstate.GetStateEnum() != State.BLOK)
        {
            <h3 class="text-center">Je kan doorgaan!</h3>
            <div><a class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent text-center" asp-controller="Groep" asp-action="StartDirect" asp-route-id="@Model.Groep.Id" role="button">Ga door</a></div>

        }
        else
        {
            <h3 class="text-center">Je kan nog niet doorgaan</h3>
        }
    </section>
    <iframe src="~/docs/@(Model.Feedback)" type="application/pdf" width="500" height="700" style="margin-bottom: 2em;"></iframe>
</div>

BreakOutBoxAuth/Views/Groep/Lounge.cshtml
@model BreakOutBoxAuth.Models.LoungeViewModel.LoungeViewModel
@{
    ViewData["Title"] = "Lounge";
    if (Model.Groep.Currentstate.GetStateEnum() == BreakOutBoxAuth.Models.Domain.State.KANSPELEN)
    {
        ViewData["KanSpelen"] = "";
    }
    else
    {
        ViewData["KanSpelen"] = "";
    }
}

@section Scripts
    {
    <script src="~/lib/signalr/signalr.js"></script>
    <script src="~/js/signalr_communication.js"></script>
    <script>
        window.sr = ScrollReveal();
        sr.reveal('.loungecard', {
            origin: 'top'
        });
    </script>

}

<meta http-equiv="refresh" content="10" />

<div class="lounge">
    <div class="container-fluid">
        <div class="loungecard">
            <h2>Lobby</h2>
            <div class="row">
                <div class="col col-md-6">
                    <div class="grpcard mdl-card mdl-shadow--2dp">
                        <div class="mdl-card__title">
                            <h2 class="mdl-card__title-text">@Model.Groep.Naam</h2>
                        </div>
                        <div class="mdl-card__supporting-text">
                            <div class="demo-list-action mdl-list">
                                @foreach (var leerling in @Model.Groep.LijstLeerlingen())
                                {
                                    <div class="mdl-list__item">
                                        <span class="mdl-list__item-primary-content">
                                            <i class="material-icons mdl-list__item-avatar">person</i>
                                            <span>@leerling</span>
                                        </span>
                                    </div>
                                }

                            </div>
                        </div>
                        <div class="mdl-card__actions mdl-card--border">
                            <label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" for="checkbox-1">
                                <input type="checkbox" disabled id="checkbox-1" checked="@Model.Groep.Contactleer? ''" class="mdl-checkbox__input">
                                <span class="mdl-checkbox__label">Contactleer</span>
                            </label>
                        </div>
                    </div>
                </div>
                <div class="col col-md-6">
                    <h3>Even Wachten...</h3>
                    <div class="wachten">
                        <span class="spinner mdl-spinner mdl-spinner--single-color mdl-js-spinner is-active"></span>
                        @if (Model.Groep.Currentstate.GetStateEnum() != BreakOutBoxAuth.Models.Domain.State.GEKOZENVERGRENDELD && Model.Groep.Currentstate.GetStateEnum() != BreakOutBoxAuth.Models.Domain.State.START)
                        {
                            <a id="startButton" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" asp-controller="Groep" asp-action="Start" asp-route-id="@Model.Groep.Id">Start</a>
                        }
                        else
                        {
                            <a id="startButton" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" asp-controller="Groep" asp-action="Start" asp-route-id="@Model.Groep.Id" disabled="disabled">Start</a>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

BreakOutBoxAuth/Views/Groep/Schatkist.cshtml
<div class="schatkist">
    <div data-toggle="modal" data-target="#skrt">
        <img class="chest" src="~/images/giphy.jpg" />
        <img src="~/images/giphy.gif" />
    </div>
    <!-- Modal -->
    <div class="modal fade" id="skrt" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Hoera! Je hebt de schatkist gevonden!</h4>
                </div>
                <div class="modal-body">
                    <p>Keer terug naar het startscherm</p>
                </div>
                <div class="modal-footer">
                    <a asp-controller="Sessie" asp-action="Index" class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored">
                        <i class="material-icons">done_outline</i>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {

    <script>
        window.sr = ScrollReveal();
        sr.reveal('.schatkist');
    </script>
}

BreakOutBoxAuth/Views/Groep/Start.cshtml
@model BreakOutBoxAuth.Models.OefeningViewModel.AntwoordViewModel

@{
    ViewData["Title"] = "Gamescherm";

}


<div class="gamescherm">
    <div class="container">
        <h1>Gamescherm</h1>
        <h2>@Model.Groep.Naam</h2>
        <a href="#oef" class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored">
            <i class="material-icons">keyboard_arrow_down</i>
        </a>
    </div>
</div>
<div class="voortgang" id="oef">
    <div class="container-fluid">
        <span>VOORTGANG:</span>
        <div class="progress" >
            <div class="progress-bar progress-bar-striped progress-bar-animated bg-info" role="progressbar" aria-valuenow="@Model.Groep.GetProgress100()" aria-valuemin="0" aria-valuemax="100" style="width: @Model.Groep.GetProgress100()%">@(Model.Groep.Progress - 1) / @(Model.Groep.GroepPad.Count)</div>
        </div>
    </div>
</div>


@Html.Partial("_Oefening", Model)

BreakOutBoxAuth/Views/Groep/index.cshtml
@model BreakOutBoxAuth.Models.Sessie

@{
    ViewData["Title"] = Model.Naam;
}
<div class="sessiebar">
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <input class="mdl-textfield__input" type="number" id="sample" value="@Model.Code" disabled>
        <label class="mdl-textfield__label" for="sample">@Model.Naam</label>
        <span class="mdl-textfield__error">Input is not a number!</span>
    </div>
</div>

<div class="secties">
    <div class="textback">
        <h2 class="container">Groep selecteren</h2>
    </div>
    <div class="container groepen">
        <div class="row">
            @foreach (var groep in Model.SessieGroep)
            {
                <div class="col-lg-3 col-sm-6">
                    <div class="circlecard mdl-shadow--2dp ">
                        <h5 class="text-center">@groep.Groepen.Naam</h5>

                        <a href="#" data-toggle="modal" data-target="#@groep.Groepen.Naam"><div class="circle"></div></a>
                        <div class="klas">@groep.Groepen.Klas</div>
                        <div class="modal fade" id="@groep.Groepen.Naam" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLongTitle">@groep.Groepen.Naam | @groep.Groepen.Klas</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" for="checkbox-2">
                                            <span class="mdl-checkbox__label">Contactleer:</span>
                                            <input type="checkbox" disabled id="checkbox-2" class="mdl-checkbox__input" @(groep.Groepen.Contactleer ? "checked" : "")>
                                        </label>
                                        <p>Leerlingen:</p>
                                        <ul class="demo-list-icon mdl-list">
                                            @foreach (var leerling in @groep.Groepen.LijstLeerlingen())
                                            {
                                                <li class="mdl-list__item">
                                                    <span class="mdl-list__item-primary-content">
                                                        <i class="material-icons mdl-list__item-icon">person</i>
                                                        @leerling
                                                    </span>
                                                </li>
                                            }
                                        </ul>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="mdl-button mdl-js-button mdl-js-ripple-effect" data-dismiss="modal">Close</button>
                                        <a class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" asp-controller="Groep" asp-action="Lounge" asp-route-id="@groep.Groepen.Id">Ja, dit zijn wij!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }

        </div>
        <a class="mdl-button mdl-button--raised mdl-js-button mdl-js-ripple-effect onderbuttontje" asp-controller="Sessie" asp-action="Index">Back</a>
    </div>
</div>
@section Scripts {

    <script>
        window.sr = ScrollReveal({duration: 1000});
        sr.reveal('.sessiebar', {
            origin: 'right',
            delay: 500
        });
        sr.reveal('.circlecard');
    </script>
}